name: task_management
description: "A Task Management app using Firebase CRUD"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  another_flushbar: ^1.12.30
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  equatable: ^2.0.7
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

