// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC7LAX2noNNZCLFEOkQgihpvBRVatI9iQ',
    appId: '1:637155831623:android:5b731cf4da9e2051d06662',
    messagingSenderId: '637155831623',
    projectId: 'clearbooks-190d4',
    databaseURL: 'https://clearbooks-190d4-default-rtdb.firebaseio.com',
    storageBucket: 'clearbooks-190d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNQEwglZc9LPXKnAXV20-7v_4_BrFLLQ',
    appId: '1:637155831623:ios:e84722798ed4d64ad06662',
    messagingSenderId: '637155831623',
    projectId: 'clearbooks-190d4',
    databaseURL: 'https://clearbooks-190d4-default-rtdb.firebaseio.com',
    storageBucket: 'clearbooks-190d4.firebasestorage.app',
    androidClientId: '637155831623-et12f85dcqmo5ht9li4ucchlprauk7md.apps.googleusercontent.com',
    iosClientId: '637155831623-qn5i0304981icop9lf8isl6ed06q6p36.apps.googleusercontent.com',
    iosBundleId: 'com.app.taskManagement',
  );
}
